name: business_card_ui
description: Digital Business Card
publish_to: 'none'
version: 1.0.4

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  vcard_maintained: ^0.0.1+1
  file_saver: ^0.2.13
  provider: ^6.1.2
  url_launcher: ^6.3.0
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  dio_cookie_manager: ^3.1.1
  url_strategy: ^0.2.0
  font_awesome_flutter: ^10.7.0
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1
  go_router: ^14.2.1
  simple_tags: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  retrofit_generator: ^8.1.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  archive: ^3.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/.env
    - assets/production.env

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#2C2540"
    theme_color: "#2C2540"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/images/logo.png"
    remove_alpha_ios: true